# site settings
title: Camila
subtitle: L. Oliveira
email: hellomilla@writeme.com
description: Página de projetos no GitHub.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Camila L. Oliveira
street_address: Av. Campy, 15
city: Carapicuiba
state: SP
zip_code: 55555
country: Brasil
phone: 


# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6



# social settings
500px_url:
facebook_url: https://fb.com/millaloliveira
github_url: https://github.com/clcmoliveira
gitlab_url: https://gitlab.com/u/millaloliveira
googleplus_url: 
instagram_url: https://instagram.com/millaloliveira
linkedin_url: https://www.linkedin.com/in/clcmdeoliveira
pinterest_url: https://pinterest.com/millaloliveira
slack_url:
twitter_url: https://twitter.com/millaloliveira

# build settings
markdown: kramdown
sass:
  style: compressed
